django_project/urls.py
from django.contrib import admin
from django.urls import path
from meusJogosFavoritos import views

urlpatterns = [
  path('home', views.home),
  path('admin/', admin.site.urls),
  path('jogos/<int:ranking>', views.jogos),
  path('newjogo', views.newJogo),
  path('editjogo/<int:id>', views.editJogo),
  path('deljogo/<int:id>', views.delJogo),
  path('', views.inicio),
  path('login', views.login_usuario),
  path('logout',views.logout_usuario)
]

meusJogosFavoritos/models.py
from django.db import models
from django.db.models.enums import Choices
from django.contrib.auth.models import User 


# Create your models here.

class Jogo(models.Model):
  nome = models.CharField(max_length=50)
  icone = models.URLField(max_length=1000)
  rank = models.IntegerField()
  descricao = models.TextField()
  data_lancamento = models.DateField()
  nota = models.DecimalField(max_digits=3, decimal_places=1)
  usuario = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.nome


class Referencia(models.Model):
  jogo = models.ForeignKey(Jogo, on_delete=models.CASCADE)
  nome = models.CharField(max_length=100)
  link = models.URLField(max_length=1000)
  tipo = models.CharField(max_length=2,
    choices = {
      "pg": "Pagina do jogo",
      "wk": "Wiki do Jogo",
      "vi": "Video do jogo",
      "jo": "Jogo na internet",
      "ou": "Outros"
    })
  favorito = models.BooleanField()

  def __str__(self):
    return self.nome

meusJogosFavoritos/forms.py
from django import forms
from django.db.models import fields
from .models import Jogo, Referencia

class JogoForm(forms.ModelForm):
  class Meta:
    model = Jogo
    exclude = ["usuario"]

meusJogosFavoritos/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Jogo, Referencia
from .forms import JogoForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def inicio(request):
  return render(request, "inicio.html")


def login_usuario(request):
  form = AuthenticationForm()
  if request.method == "POST" and request.POST:
    form = AuthenticationForm(request, request.POST)
    if form.is_valid():
      user = form.get_user()
      login(request, user)
      return redirect("/home")
  return render(request,"login.html",{"formulario": form})

@login_required
def home(request):

  jogos = Jogo.objects.order_by("rank").filter(usuario=request.user).all()

  return render(request, 'home.html', {"jogos": jogos})

@login_required
def jogos(request, ranking):

  jogo = get_object_or_404(Jogo, rank=ranking, usuario=request.user)

  return render(request, 'jogos.html', {"jogo": jogo})

@login_required
def newJogo(request):
  formulario = JogoForm()

  if request.method == "POST" and request.POST:
    formulario = JogoForm(request.POST)

    if formulario.is_valid():
      jogo = formulario.save(commit=False)
      jogo.usuario = request.user
      jogo.save()
      return redirect("/home")

  return render(request, "newjogo.html", {"formulario": formulario})

@login_required
def editJogo(request, id):
  jogo = get_object_or_404(Jogo, pk=id, usuario=request.user)
  formulario = JogoForm(instance=jogo)

  if request.method == "POST" and request.POST:
    formulario = JogoForm(request.POST, instance=jogo)

    if formulario.is_valid():
      formulario.save()
      return redirect("/home")

  return render(request, "editjogo.html", {"formulario": formulario})

@login_required
def delJogo(request, id):
  jogo = get_object_or_404(Jogo, pk=id, usuario=request.user)

  if request.method == "POST" and request.POST:
    jogo.delete()
    return redirect("/home")

  return render(request, "deljogo.html", {"jogo": jogo})

@login_required
def logout_usuario(request):
  logout(request)
  return redirect("/")

meusJogosFavoritos/templates/deljogo.html
<!DOCTYPE html>
<html>

<p>Você tem ceteza que deseja remover o jogo {{jogo.nome}} do banco de dados?</p>
  
<form method="POST">
  {% csrf_token %}
  <button type="submit">Remover</button>
</form>

</html>

meusJogosFavoritos/templates/editjogo.html
<!DOCTYPE html>
<html>

<form method="POST">
  {% csrf_token %}
  {{ formulario }}
  <button type="submit">Salvar</button>
</form>

</html>

meusJogosFavoritos/templates/home.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <link href="{% static 'style.css' %}" rel="stylesheet">
  
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>replit</title>
  <link href="style.css" rel="stylesheet" type="text/css" />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Pacifico&display=swap" rel="stylesheet">
</head>

<body>
  <div class ="textoTodo">
    <h1>{{titulo}}</h1>
    <h3 class= "cabecalho">Aluno: Gustavo Braga</h3>
    <h3 class= "cabecalho">Matricula: 2311958</h3>

    <p>
      Nesta pagina eu listarei alguns dos meus jogos favoritos. Claramente esses jogos são melhores então quem discordar esta errado.
    </p>

    <p>
      Mas de qualquer modo, eu tenho o meu gosto e voce o seu (mas o meu é melhor) e este consiste em jogos mais para aventura e puzzle.
    </p>

    <div class= "imagem1">
    <img src="https://files.meiobit.com/wp-content/uploads/2015/11/20151124xbox-controller.jpg" width= 400>
    </div>

    <h2 class="tituloLista">Lista dos meus jogos favoritos</h2>
    <a style="font-size: 20px"href="/newjogo">Adicionar jogo</a>
    <ol>
      {% for jogo in jogos %}
      <li style="font-size: 20px">
        <img src= {{jogo.icone}} width=100>
        <a class = "miniTitulo">{{jogo.nome}}</a>
        
        <a href ="/editjogo/{{jogo.id}}">Editar jogo</a>
        <a href="/deljogo/{{jogo.id}}">Deletar jogo</a>
        <ul>
          {% for referencia in jogo.referencia_set.all %}
          <li>
            <i><a href={{referencia.link}} class="links">{{referencia.nome}}</a></i>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </ol>

    <h2 class="tituloLista">Tabela dos generos dos jogos</h2>
    <table>
      <tr class ="linha1">
        <th>Aventura</th>
        <th>Puzzle</th>
        <th>Tiro</th>
      </tr>
      <tr class="linha2">
        <td>Hollow knight</td>
        <td>Baba is you</td>
        <td>Borderlands 2</td>
      </tr>
      <tr class="linha1">
        <td>Outer wilds</td>
        <td>Heart and soul</td>
        <td></td>
      </tr>
    </table>

    <a style="font-size: 20px"href="/logout">Sair</a>

  </div>

</body>

</html>

meusJogosFavoritos/templates/inicio.html
<p>Ola! Venha se logar para poder acessar a pagina!</p>
<a href="/login">Login</a>

meusJogosFavoritos/templates/jogos.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <link href="{% static 'style.css' %}" rel="stylesheet">
  
  
</head>

<body>

  <h1>{{jogo.nome}}</h1>

  <div class= "imagem1">
  <img src= {{jogo.icone}} width= 400>
  </div>

  <p>{{jogo.descricao}}</p>
  
</body>

</html>

meusJogosFavoritos/templates/login.html
<form method="POST">
  {% csrf_token %}
  {{formulario}}
  <button type="submit">Entrar</button>
</form>

meusJogosFavoritos/templates/newjogo.html
<!DOCTYPE html>
<html>

<form method="POST">
  {% csrf_token %}
  {{ formulario }}
  <button type="submit">Salvar</button>
</form>

</html>